ALTER TABLE rapports
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ADD COLUMN IF NOT EXISTS created_by VARCHAR(100),
    ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);


-- ALTER TABLE utilisateurs ADD COLUMN IF NOT EXISTS ... (même 4 lignes)
-- ALTER TABLE documents ADD COLUMN IF NOT EXISTS ...
-- ALTER TABLE taches ADD COLUMN IF NOT EXISTS ...